name: Java CI with Gradle

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
      
    - name: Build with Gradle
      run: |
        ./gradlew --version
        ./gradlew build # 빌드 
        
    - name: Upload S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SECRET_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
          --region ap-northeast-2 \
          ./build/libs/*.jar s3://sicpamabucket
