name: Deploy # Workflow 이름
on: # Event 감지
  push:
    branches:
      - main # 마스터 브랜치의 푸쉬가 일어날 때 CI/CD를 진행하겠다는 뜻
jobs: # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2
      - name: Install Dependencies # 의존 파일 설치
        run: yarn install --frozen-lockfile
      - name: Build # React Build
        run: yarn build
      - name: zip create 
        run: zip -qq -r ./build-fe.zip .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SECRET_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://sicpamabucket/sicpama_folder/build-fe.zip
      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name sicpama2
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name sicpama2_group
          --s3-location bucket=sicpamabucket,key=sicpama_folder/build-fe.zip,bundleType=zip
