name: CD with Node

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: zip 생성
        run: zip -qq -r ./build-fe.zip .
        shell: bash

      - name: AWS 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SECRET_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: S3 업로드
        run: aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://codesquad-deploy/client/build-fe.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name sicpama2 --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name sicpama2_group --s3-location bucket=sicpamabucket,bundleType=zip,key=client/build-fe.zip
